<div><a href="{{ route('waongpa.rooms.show',['roomId'=>$round->room_id]) }}">← {{ $round->room->name }}</a><p class="eyebrow">รอบที่ {{ $round->round_no }}</p><h1>เวลานัดหมายของเรา</h1><p><span class="badge">{{ $round->phase }}</span> {{ $round->duration_minutes }} นาที · {{ $round->daily_start_time }}–{{ $round->daily_end_time }}</p>@include('waongpa.feedback')
@if($round->version!==$version)<p class="error">รอบนี้ถูกรีเซ็ตแล้ว <a href="{{ route('waongpa.rounds.show',['roundId'=>$round->id]) }}">โหลดหน้าใหม่</a></p>@endif
@if($isMember)<p class="notice">ยืนยันตาราง {{ $confirmedCount }}/{{ $peopleCount }} คน · เริ่มโหวต {{ $round->voting_starts_at->format('d/m H:i') }} · ปิดโหวต {{ $round->final_starts_at->format('d/m H:i') }}</p>@endif
@if($isOwner && $round->phase!=='final')<div class="actions"><button wire:loading.attr="disabled" wire:confirm="ข้ามไปเฟสถัดไปทันที? ระบบยังตรวจข้อมูลที่จำเป็น" wire:click="advance">ข้ามไปเฟสถัดไป</button><button class="secondary" wire:click="syncDue">อัปเดตเฟสตามเวลา</button></div>@endif
@if($person && $round->phase==='join')<section class="panel"><h2>ตารางของฉันในรอบนี้</h2><p>สถานะ {{ $person->schedule_confirmed_at?'ยืนยันแล้ว':'ยังไม่ยืนยัน' }}</p><div class="actions"><button class="secondary" wire:confirm="แทนตารางของรอบนี้ด้วย My Schedule ล่าสุด? การแก้เฉพาะรอบจะถูกแทนที่" wire:click="syncSchedule">ดึง My Schedule ใหม่</button><button wire:confirm="ยืนยันว่าตารางครบแล้ว? ถ้าไม่มีรายการ หมายถึงว่างตลอดช่วงค้นหา" wire:click="confirm">ยืนยันตารางพร้อมใช้</button></div>
<form wire:submit="saveBusy">@include('waongpa.event-fields')<button>{{ $editing?'บันทึกการแก้ไข':'เพิ่มช่วงไม่ว่างเฉพาะรอบ' }}</button>@if($editing)<button type="button" class="secondary" wire:click="clear">ยกเลิก</button>@endif</form>
<div class="table-wrap"><table><thead><tr><th>กิจกรรม</th><th>ช่วงเวลา</th><th>จัดการ</th></tr></thead><tbody>@forelse($person->busyPeriods as $busy)<tr wire:key="busy-{{ $busy->id }}"><td>{{ $busy->title }}</td><td>{{ $busy->starts_at->format('d/m H:i') }} – {{ $busy->ends_at->format('d/m H:i') }}</td><td><button class="secondary" wire:click="editBusy({{ $busy->id }})">แก้ไข</button> <button class="danger" wire:confirm="ลบช่วงไม่ว่างนี้จากรอบ?" wire:click="deleteBusy({{ $busy->id }})">ลบ</button></td></tr>@empty<tr><td colspan="3">ยังไม่มีช่วงไม่ว่าง หากว่างทั้งหมดให้กดยืนยันตาราง</td></tr>@endforelse</tbody></table></div></section>@endif
@if($isMember && $timeOptions->isNotEmpty())<h2>ช่วงเวลาที่เสนอ</h2><div class="grid three">@foreach($timeOptions as $slot)<section class="panel" wire:key="slot-{{ $slot->id }}"><span class="badge">อันดับ {{ $slot->rank_no }}</span><h2>{{ $slot->starts_at->format('d/m/Y') }}</h2><p class="time">{{ $slot->starts_at->format('H:i') }}–{{ $slot->ends_at->format('H:i') }}</p><p>คะแนนความพร้อม {{ $slot->weighted_score }}<br>คะแนนโหวต {{ $slot->votes_count }}</p>@if($person && $round->phase==='voting')<button wire:loading.attr="disabled" wire:click="vote({{ $slot->id }})">{{ $person->vote?->time_slot_id===$slot->id?'เลือกไว้แล้ว':'โหวตเวลานี้' }}</button>@endif</section>@endforeach</div>@endif
@if($result)<section class="panel result"><p class="eyebrow">นัดหมายที่สรุปแล้ว</p><h2>{{ $result->slot->starts_at->format('d/m/Y H:i') }} – {{ $result->slot->ends_at->format('H:i') }}</h2><p>{{ ['most_votes'=>'ได้รับโหวตสูงสุด','tie_earliest'=>'คะแนนเสมอ เลือกเวลาเร็วสุด','no_votes_top_rank'=>'ไม่มีโหวต เลือกอันดับแรกของระบบ'][$result->decision_reason] }}</p>@if($isMember)<a class="button" href="{{ route('waongpa.rounds.ics',['roundId'=>$round->id]) }}">ดาวน์โหลดนัด .ics</a>@endif</section>@elseif(!$isMember)<p class="panel">รอบนี้ยังไม่มีผลนัดที่ประกาศ รายละเอียดตารางและการโหวตแสดงเฉพาะสมาชิก</p>@endif</div>
